
//----------------------------------------------------
// The following code was generated by CUP v0.10k TUM Edition 20050516
// Sat Oct 10 13:56:47 PDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_WHILE = 61;
  public static final int T_INT_LITERAL = 66;
  public static final int T_FLOAT = 25;
  public static final int T_LTE = 37;
  public static final int T_ELSE = 19;
  public static final int T_STATIC = 56;
  public static final int T_RPAREN = 51;
  public static final int T_DELETE = 64;
  public static final int T_CONTINUE = 16;
  public static final int T_COUT = 17;
  public static final int T_SIZEOF = 53;
  public static final int T_NULLPTR = 43;
  public static final int T_FALSE = 24;
  public static final int T_INT = 31;
  public static final int T_MINUSMINUS = 39;
  public static final int T_EXTERN = 23;
  public static final int T_ASSIGN = 5;
  public static final int T_BAR = 7;
  public static final int T_RETURN = 50;
  public static final int T_NOT = 42;
  public static final int T_AND = 3;
  public static final int T_CONST = 15;
  public static final int T_SLASH = 54;
  public static final int T_COLONCOLON = 13;
  public static final int T_GT = 28;
  public static final int T_STRUCTDEF = 57;
  public static final int T_RBRACKET = 49;
  public static final int T_DOT = 18;
  public static final int EOF = 0;
  public static final int T_MINUS = 38;
  public static final int T_TILDE = 59;
  public static final int T_LBRACE = 33;
  public static final int error = 1;
  public static final int T_NEW = 63;
  public static final int T_SEMI = 52;
  public static final int T_ID_U = 68;
  public static final int T_FLOAT_LITERAL = 65;
  public static final int T_MOD = 40;
  public static final int T_RBRACE = 48;
  public static final int T_NEQ = 41;
  public static final int T_CIN = 11;
  public static final int T_COMMA = 14;
  public static final int T_STAR = 55;
  public static final int T_GTE = 29;
  public static final int T_ENDL = 20;
  public static final int T_EQU = 21;
  public static final int T_CARET = 10;
  public static final int T_BOOL = 8;
  public static final int T_PLUS = 46;
  public static final int T_EXIT = 22;
  public static final int T_LT = 36;
  public static final int T_STR_LITERAL = 67;
  public static final int T_THIS = 58;
  public static final int T_OR = 44;
  public static final int T_AMPERSAND = 2;
  public static final int T_BREAK = 9;
  public static final int T_TRUE = 60;
  public static final int T_ISTREAM = 32;
  public static final int T_FOREACH = 26;
  public static final int T_OSTREAM = 45;
  public static final int T_IF = 30;
  public static final int T_PLUSPLUS = 47;
  public static final int T_ARROW = 4;
  public static final int T_ID = 69;
  public static final int T_COLON = 12;
  public static final int T_FUNCTION = 27;
  public static final int T_AUTO = 6;
  public static final int T_VOID = 62;
  public static final int T_LBRACKET = 34;
  public static final int T_LPAREN = 35;
}

